# Generated by Django 3.0.8 on 2021-04-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('projects_image', models.ImageField(upload_to='')),
                ('project_domain', models.CharField(max_length=40)),
                ('project_gitlink', models.CharField(max_length=40)),
                ('project_demo', models.CharField(max_length=40)),
            ],
        ),
    ]
