# Generated by Django 3.0.8 on 2021-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210419_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='domainname',
            field=models.CharField(default=32, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='domain',
        ),
    ]
